source 'https://rubygems.org'

gem 'rake', '~> 10.0'
gem 'sinatra', '~> 1.4'
gem 'thin', '~> 1.5'
gem 'rspec', '~> 2.13'
gem 'capybara', '~> 2.1'
gem 'haml', '~> 4.0'
gem 'barista', '~> 1.3'
gem 'poltergeist', '~> 1.2'